Repository TexasTorque/TorqueLib, pull requests merged in 2023-02, with the labels that each got.

#17 FEATURE General Cleanup
  control/TorqueBoolSupplier.java
  control/TorqueCurrentSpike.java
  control/TorqueLogisticRegression.java
  legacy/TorqueToggleLegacy.java
  util/TorqueUtil.java
Labels: FEATURE

#18 FEATURE New NEO setters
  control/TorqueBoolSupplier.java
  control/TorqueCurrentSpike.java
  control/TorqueLogisticRegression.java
  legacy/TorqueToggleLegacy.java
  motors/TorqueNEO.java
  util/TorqueUtil.java
Labels: FEATURE

#19 FEATURE Auto cleanup
  auto/commands/TorqueSequenceRunner.java
  auto/commands/TorqueWaitForSeconds.java
  auto/commands/TorqueWaitUntil.java
Labels: FEATURE

#21 BUG FIX Remove fatal import error
  auto/commands/TorqueSequenceRunner.java
Labels: BUG FIX

#22 FEATURE Add TorqueContinous
  auto/commands/TorqueContinuous.java
Labels: FEATURE

#23 FEATURE Torque chassis speeds
  auto/TorqueAutoManager.java
  base/TorqueRobotBase.java
  sensors/TorqueVision.java
  swerve/TorqueSwerveModule2021.java
  swerve/TorqueSwerveModule2022.java
  swerve/TorqueSwerveSpeeds.java
  swerve/base/TorqueSwerveModule.java
  swerve/base/package-info.java
  swerve/base/readme.md
  swerve/package-info.java
  swerve/readme.md
Labels: FEATURE

#24 REFACTOR Formatted with organize fields
  auto/TorqueAutoManager.java
  auto/TorqueSequence.java
  auto/commands/TorqueContinuous.java
  auto/commands/TorqueGeneric.java
  auto/commands/TorqueSequenceRunner.java
  auto/commands/TorqueWaitForSeconds.java
  auto/commands/TorqueWaitUntil.java
  base/TorqueDirection.java
  base/TorqueInputModule.java
  base/TorqueRobotBase.java
  control/TorqueCondition.java
  control/TorqueCurrentSpike.java
  control/TorqueLogisticRegression.java
  control/TorqueLookUpTable.java
  control/TorquePID.java
  control/TorqueRollingMedian.java
  control/TorqueWestCoast.java
  control/test/Test.java
  legacy/GenericController.java
  legacy/TorqueFalcon.java
  legacy/TorqueLogiPro.java
  legacy/TorqueSparkMax.java
  legacy/TorqueTalon.java
  legacy/base/TorqueEncoderMotor.java
  motors/TorqueNEO.java
  scripts/add_license.py
  sensors/TorqueColorSensor.java
  sensors/TorqueController.java
  sensors/TorqueLight.java
  sensors/TorqueNavXGyro.java
  sensors/TorqueVision.java
  sensors/util/TorqueAprilTagMap.java
  swerve/TorqueSwerveModule2021.java
  swerve/TorqueSwerveModule2022.java
  swerve/TorqueSwerveSpeeds.java
  util/TorqueMath.java
  util/TorqueUtil.java
Labels: REFACTOR

#26 Feature TorqueCANCoder
  sensors/TorqueCANCoder.java
Labels: FEATURE

#27 BUG FIX TorqueCANCoder isCANResponsive() fixed
  sensors/TorqueCANCoder.java
Labels: BUG FIX

#28 FEATURE Update PhotonVision to use MULTI_TAG_PNP
  sensors/TorqueVision.java
Labels: FEATURE

#29 FEATURE TorqueSwerveSpeeds times overload
  swerve/TorqueSwerveSpeeds.java
Labels: FEATURE

#30 REFACTOR TorqueRequestableTimeout rename calculate() to get()
  control/TorqueRequestableTimeout.java
Labels: REFACTOR

#31 FEATURE TorqueTraversableSelection rename getters
  control/TorqueTraversableSelection.java
Labels: FEATURE

#32 BUG FIX TorqueAutoManager selection fixed
  auto/TorqueAutoManager.java
Labels: BUG FIX

#33 FEATURE TorqueNEO add brake mode
  motors/TorqueNEO.java
Labels: FEATURE
